<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AgentCore\AgentCore.csproj" />
    <ProjectReference Include="..\..\AgentCore.Layers\AgentCore.Layers.csproj" />
    <ProjectReference Include="D:\CodeBase\Popular Agent Frameworks\microsoft-agent-framework\dotnet\src\Microsoft.Agents.AI\Microsoft.Agents.AI.csproj" />
  </ItemGroup>

</Project>
